CC = gcc

OFILES = $(SRCS:.c=.o)

CFLAGS = -Wall -Wextra -Werror -g

SRC = ./ft_atoi.c     ./ft_itoa.c      ./ft_putchar_fd.c  ./ft_strlcat.c  ./ft_strtrim.c ./ft_bzero.c ./ft_memchr.c    ./ft_putendl_fd.c  ./ft_strlcpy.c  ./ft_substr.c ./ft_calloc.c   
	./ft_memcmp.c    ./ft_putnbr_fd.c   ./ft_strlen.c   ./ft_tolower.c ./ft_isalnum.c  ./ft_memcpy.c    ./ft_strchr.c      ./ft_strmapi.c  ./ft_toupper.c
	./ft_isalpha.c  ./ft_memmove.c   ./ft_strdup.c      ./ft_strncmp.c  
	./ft_isascii.c  ./ft_memset.c    ./ft_striteri.c    ./ft_strnstr.c ./ft_isdigit.c  ./ft_pustr_fd.c  ./ft_strjoin.c     ./ft_strrchr.c

NAME = libft.a

ar rcs 

all : $(NAME) clean

$(NAME): $(OFILES)
	ar rcs $(NAME) $(OFILES)

clean:
	rm -f $(NAME)

fclean:
	clean rm -f $(NAME)

re: fclean $(NAME)

.PHONY: all clean fclean re


